- name: detect if redis installed
  block:
    - name: collect package files
      package_facts:
        manager: "auto"

    - name: detect if redis installed
      set_fact:
        redis_present: true
      when: "'redis' in ansible_facts.packages"

- name: detect if redis and sentinel started
  block:
    - name: populate service facts
      service_facts:
      when: redis_present

    - name: detect if redis started
      set_fact:
        redis_started: true
      when: redis_present and "ansible_facts.services['redis.service']['state'] == 'running'"

    - name: check redis-sentinel service exists
      set_fact:
        redis_sentinel_exists: true
      when: redis_present and ansible_facts.services['redis-sentinel.service'] is defined

    - name: detect if redis-sentinel started
      set_fact:
        redis_sentinel_started: true
      when: redis_sentinel_exists

- name: detect current redis master
  block:
    - name: get cluster master
      shell: redis-cli -h 127.0.0.1 -p {{ redis_listen_port }} info replication | grep role:master
      register: redis_sentinel_is_master
      tags: skip_ansible_lint
      when: redis_started and redis_sentinel_started
      ignore_errors: true

    - name: set current master in fact
      set_fact:
        redis_master: true
      when: redis_sentinel_is_master.rc == 0
      run_once: true

    - name: set current master ip in fact
      set_fact:
        redis_master_ip: "{{ inventory_hostname }}"
      when: redis_master
      run_once: true

    - name: set current master name in fact
      set_fact:
        redis_master_name: "{{ ansible_hostname }}"
      when: redis_master
      run_once: true

    - name: or use default first host
      set_fact:
        redis_master: true
      when: redis_master_ip == '127.0.0.1' and inventory_hostname == play_hosts[0]

    - name: and remember master's ip
      set_fact:
        redis_master_ip: "{{ hostvars[play_hosts.0]['ansible_default_ipv4']['address'] }}"
        redis_master_name: "{{ hostvars[play_hosts.0]['hostname'] }}"
      when: redis_master_ip == '127.0.0.1'
      run_once: true

    # - name: fill SLAVEOF
    #   set_fact:
    #     redis_slaveof: "{{ redis_master_ip }}"
    #   when: not redis_master
