---

- name: create sentinel config file
  template:
    src: redis-sentinel.conf
    dest: /etc/redis/sentinel.conf
    owner: "{{ redis_user }}"
    group: "{{ redis_user }}"
    mode: 0640
  notify: restart sentinel

- name: create redis config file
  template:
    src: redis.conf
    dest: /etc/redis/redis.conf
    owner: "{{ redis_user }}"
    mode: 0640
  notify: restart redis cluster

# - name: override systemd unit
#   copy:
#     src: override.conf
#     dest: /etc/systemd/system/redis-sentinel.service.d/override.conf
#   notify: restart sentinel

- name: put service check script
  template:
    src: check-redis.sh.j2
    dest: /usr/local/sbin/check-redis.sh
    mode: 0755
    owner: root
    group: root

# in debian redis always tried to red /etc/redis.conf
- name: create config symlink
  file:
    src: /etc/redis/redis.conf
    dest: /etc/redis.conf
    state: link
