---

- name: Install haproxy
  yum: name=haproxy state=present
  when: ansible_distribution == 'CentOS'
  register: haproxy_installed

- name: Install haproxy
  dnf: name=haproxy state=present
  when: ansible_distribution == 'Fedora'
  register: haproxy_installed

- name: Adding sysctl keys for haproxy
  sysctl: name={{ item }} value=1 state=present
  loop:
    - "net.ipv4.ip_forward"
    - "net.ipv4.ip_nonlocal_bind"

- name: generate haproxy config
  block:
    - name: create temp file
      tempfile:
        state: file
        suffix: temp
      register: temp_file
      delegate_to: localhost
      become: false
    
    - name: generate Haproxy config blank
      copy:
        content: "{{ haproxy_base_config + haproxy_service_config }}"
        dest: "{{ temp_file.path }}"
      delegate_to: localhost

    - name: put haproxy config
      template:
        src: "{{ temp_file.path }}"
        dest: /etc/haproxy/haproxy.cfg
      notify: restart haproxy

    - name: remove the temporary file
      file:
        path: "{{ temp_file.path }}"
        state: absent
      when: temp_file.path is defined
      delegate_to: localhost
