---
# handlers file for redis.role

- name: restart redis slaves
  systemd:
    name: redis
    state: restarted
    enabled: yes
    daemon_reload: yes
  when: ansible_virtualization_type != 'docker' and not redis_master
  listen: restart redis cluster

- name: restart redis master
  systemd:
    name: redis
    state: restarted
    enabled: yes
    daemon_reload: yes
  when: ansible_virtualization_type != 'docker' and not redis_master
  listen: restart redis cluster

- name: restart sentinel
  systemd:
    name: redis-sentinel
    state: restarted
    enabled: yes
    daemon_reload: yes
  when: ansible_virtualization_type != 'docker'

- name: restart haproxy
  systemd:
    state: restarted
    name: haproxy
    enabled: yes
    daemon_reload: yes

